version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3002:3000'
    volumes:
      - ./realDB:/app/realDB
      - ./public/kontak:/app/public/kontak
    command: "npm run start"
    restart: always

volumes:
  dev-db:
